### ISSUE TITLE
ARM support

### ISSUE THREAD

**Issue by rotarur** [bitnami/bitnami-docker-redis-exporter#1]
### Name and Version

bitnami/redis-exporter

### What is the problem this feature will solve?

There is no ARM support. Are there any plans to support multiplatform architecture? ARM64 and AMD64

### What is the feature you are proposing to solve the problem?

ARM support

### What alternatives have you considered?

Creating multiplatform image by myself

**Comment by carrodher** [comment]
Hi, we have created this issue https://github.com/bitnami/charts/issues/7305 that is pinned in the Bitnami Helm Charts repository, on this way we can funnel all the conversation in a single place regarding ARM64 support.

We will close the rest of the existing issues just to avoid duplications, please visit the above-mentioned issue to see any new (when possible) about this topic.
